version: '3.1'

services:
  eso_db:
    image: postgres:16-alpine
    container_name: eso_postgres_db
    environment:
      POSTGRES_USER: esodev
      POSTGRES_PASSWORD: esodevpassword
      POSTGRES_DB: eso_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
