# Generated by Django 4.2.6 on 2023-10-20 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alternative_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Bilateral', 'Bilateral'), ('Unilateral', 'Unilateral')], max_length=15, null=True)),
                ('link_to_image', models.URLField(max_length=255, null=True)),
                ('link_to_thumbnail', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alternative_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=15)),
                ('compound_movement', models.BooleanField(default=False)),
                ('link_to_image', models.URLField(max_length=255, null=True)),
                ('link_to_thumbnail', models.URLField(max_length=255, null=True)),
                ('link_to_video', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alternative_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('link_to_image', models.URLField(max_length=255, null=True)),
                ('link_to_thumbnail', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('sequence', models.CharField(choices=[('Weekly', 'Weekly'), ('Cycle', 'Cycle')], default='Weekly', max_length=10)),
                ('duration', models.PositiveSmallIntegerField()),
                ('link_to_image', models.URLField(max_length=255, null=True)),
                ('link_to_thumbnail', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('variant', models.CharField(max_length=5, null=True)),
                ('target', models.CharField(choices=[('Full Body', 'Full Body'), ('Upper Body', 'Upper Body'), ('Lower Body', 'Lower Body'), ('Anterior Muscles', 'Anterior Muscles'), ('Posterior Muscles', 'Posterior Muscles'), ('Mixed muscles', 'Mixed muscles')], default='Mixed muscles', max_length=20, null=True)),
                ('link_to_image', models.URLField(max_length=255, null=True)),
                ('link_to_thumbnail', models.URLField(max_length=255, null=True)),
                ('exercises', models.ManyToManyField(to='fitness.exercise')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.trainingtype')),
            ],
        ),
        migrations.AddIndex(
            model_name='trainingtype',
            index=models.Index(fields=['name'], name='fitness_tra_name_c62927_idx'),
        ),
        migrations.AddField(
            model_name='program',
            name='types',
            field=models.ManyToManyField(null=True, to='fitness.trainingtype'),
        ),
        migrations.AddField(
            model_name='program',
            name='workouts',
            field=models.ManyToManyField(to='fitness.workout'),
        ),
        migrations.AddIndex(
            model_name='muscle',
            index=models.Index(fields=['name'], name='fitness_mus_name_79e341_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisetype',
            index=models.Index(fields=['name'], name='fitness_exe_name_2b9093_idx'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipments',
            field=models.ManyToManyField(to='fitness.equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='main_muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_exercise_set', to='fitness.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(related_name='secondary_exercise_set', to='fitness.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ManyToManyField(to='fitness.exercisetype'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='fitness_equ_name_ef264f_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['name'], name='fitness_wor_name_bd6075_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='fitness_pro_name_61b691_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='fitness_exe_name_91210a_idx'),
        ),
    ]
