# Generated by Django 4.2.6 on 2023-10-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipments',
            field=models.ManyToManyField(blank=True, to='fitness.equipment'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, related_name='secondary_exercise_set', to='fitness.muscle'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='types',
            field=models.ManyToManyField(blank=True, to='fitness.exercisetype'),
        ),
    ]
