# Generated by Django 4.2.6 on 2023-10-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_program_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='muscle',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='exerciseplan',
            name='superset_exercise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superset_exerciseplan_set', to='fitness.exercise'),
        ),
    ]
