# Generated by Django 4.2.6 on 2023-10-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_equipment_alternative_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='workout_plans',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise_plans',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.program'),
        ),
    ]
