# Generated by Django 4.2.6 on 2023-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_workoutexerciseplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programworkoutplan',
            name='sequence',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Cycle', 'Cycle')], default='Weekly', max_length=10),
        ),
    ]
