# Generated by Django 4.2.6 on 2023-10-21 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_programworkoutplan_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExerciseRoutine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_sets', models.PositiveSmallIntegerField(default=3)),
                ('max_sets', models.PositiveSmallIntegerField(default=4)),
                ('min_reps', models.PositiveSmallIntegerField(default=8)),
                ('max_reps', models.PositiveSmallIntegerField(default=15)),
                ('tempo_eccentric', models.PositiveSmallIntegerField(default=1)),
                ('tempo_pause_1', models.PositiveSmallIntegerField(default=1)),
                ('tempo_concentric', models.PositiveSmallIntegerField(default=1)),
                ('tempo_pause_2', models.PositiveSmallIntegerField(default=1)),
                ('min_rir', models.PositiveSmallIntegerField(default=0)),
                ('max_rir', models.PositiveSmallIntegerField(default=3)),
                ('superset', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_workoutexerciseroutine_set', to='fitness.exercise')),
                ('superset_exercise', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superset_workoutexerciseroutine_set', to='fitness.exercise')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProgramWorkoutPlan',
            new_name='ProgramWorkoutRoutine',
        ),
        migrations.DeleteModel(
            name='WorkoutExercisePlan',
        ),
    ]
